//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryPri
{
    using System;
    using System.Collections.Generic;
    
    public partial class manInfo
    {
        public int manTookFIO { get; set; }
        public Nullable<int> booksId { get; set; }
        public Nullable<System.DateTime> dateTook { get; set; }
        public Nullable<int> biletId { get; set; }
        public Nullable<System.DateTime> dateGave { get; set; }
        public Nullable<bool> took { get; set; }
    
        public virtual bilet bilet { get; set; }
        public virtual Books Books { get; set; }
    }
}
